In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

In [3]:
data= fetch_california_housing()

In [96]:
X=pd.DataFrame(data.data, columns=data.feature_names)
X.head()

X=X.iloc[:,:-2]

In [97]:
y=pd.DataFrame(data.target, columns=data.target_names)
y.head()

MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16512, 6), (4128, 6), (16512, 1), (4128, 1))

In [99]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [100]:
X_train_scaled.shape

(16512, 6)

In [101]:
y.MedHouseVal.values

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [102]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense
from keras.models import Sequential

In [113]:
LAYERS = [Dense(20,input_shape=(6,), activation=tf.keras.activations.relu, name='hidden_layer1'),
          Dense(20, activation = tf.keras.activations.relu, name='hidden_layer2'),
          Dense(20, activation = tf.keras.activations.relu, name='hidden_layer3'),
          Dense(1, name='op_layer')]

OPTIMIZER = tf.keras.optimizers.Adam(1e-3)
LOSS = tf.keras.losses.MSE

In [114]:
model = Sequential(LAYERS)
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_layer1 (Dense)       (None, 20)                140       
                                                                 
 hidden_layer2 (Dense)       (None, 20)                420       
                                                                 
 hidden_layer3 (Dense)       (None, 20)                420       
                                                                 
 op_layer (Dense)            (None, 1)                 21        
                                                                 
Total params: 1,001
Trainable params: 1,001
Non-trainable params: 0
_________________________________________________________________


In [115]:
model.layers

In [116]:
for layer in model.layers:
  print(layer.variables)

[<tf.Variable 'hidden_layer1/kernel:0' shape=(6, 20) dtype=float32, numpy=
array([[-3.53888392e-01,  1.25377774e-01,  1.58770680e-01,
         2.78926373e-01,  1.41533613e-02, -3.34827185e-01,
        -1.49205953e-01,  4.80138481e-01,  3.79783869e-01,
        -2.67449617e-01, -3.42263460e-01, -2.61647642e-01,
         3.22960556e-01, -3.90643179e-02, -1.08629912e-01,
         1.83157027e-02,  2.79819608e-01,  1.34299695e-02,
        -3.10128927e-01,  3.14067245e-01],
       [ 9.15652514e-02, -4.24501032e-01, -4.25278723e-01,
         3.18690360e-01,  2.14874744e-04,  4.10130620e-01,
        -4.18610394e-01, -9.26486254e-02, -3.15241545e-01,
         2.27367878e-01,  1.38347447e-01, -1.53163850e-01,
         1.60621047e-01,  3.37562680e-01,  3.36363971e-01,
        -2.27001637e-01, -1.96710855e-01,  3.14818680e-01,
         5.76077104e-02,  3.64880443e-01],
       [-2.93566823e-01,  2.95386314e-02, -4.09830332e-01,
         2.05805779e-01,  4.41610277e-01,  2.19953537e-01,
        -2.57

In [117]:
weights,bias=model.layers[0].get_weights()

In [118]:
weights

array([[-3.53888392e-01,  1.25377774e-01,  1.58770680e-01,
         2.78926373e-01,  1.41533613e-02, -3.34827185e-01,
        -1.49205953e-01,  4.80138481e-01,  3.79783869e-01,
        -2.67449617e-01, -3.42263460e-01, -2.61647642e-01,
         3.22960556e-01, -3.90643179e-02, -1.08629912e-01,
         1.83157027e-02,  2.79819608e-01,  1.34299695e-02,
        -3.10128927e-01,  3.14067245e-01],
       [ 9.15652514e-02, -4.24501032e-01, -4.25278723e-01,
         3.18690360e-01,  2.14874744e-04,  4.10130620e-01,
        -4.18610394e-01, -9.26486254e-02, -3.15241545e-01,
         2.27367878e-01,  1.38347447e-01, -1.53163850e-01,
         1.60621047e-01,  3.37562680e-01,  3.36363971e-01,
        -2.27001637e-01, -1.96710855e-01,  3.14818680e-01,
         5.76077104e-02,  3.64880443e-01],
       [-2.93566823e-01,  2.95386314e-02, -4.09830332e-01,
         2.05805779e-01,  4.41610277e-01,  2.19953537e-01,
        -2.57830024e-02,  4.18423474e-01,  1.08486414e-02,
        -3.51761878e-01, -1.3

In [119]:
bias

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [120]:
model.compile(optimizer=OPTIMIZER, loss='mse', metrics=['accuracy'] )

In [ ]:
model.fit(X_train_scaled, y_train, epochs=50, batch_size=32, verbose=2, validation_split=0.10)

Epoch 1/50
465/465 - 1s - loss: 1.3705 - accuracy: 0.0024 - val_loss: 0.5834 - val_accuracy: 0.0030 - 925ms/epoch - 2ms/step
Epoch 2/50
465/465 - 0s - loss: 0.5385 - accuracy: 0.0026 - val_loss: 0.5090 - val_accuracy: 0.0030 - 450ms/epoch - 968us/step
Epoch 3/50
465/465 - 0s - loss: 0.4933 - accuracy: 0.0026 - val_loss: 0.4847 - val_accuracy: 0.0030 - 479ms/epoch - 1ms/step
Epoch 4/50
465/465 - 0s - loss: 0.4745 - accuracy: 0.0026 - val_loss: 0.4768 - val_accuracy: 0.0030 - 492ms/epoch - 1ms/step
Epoch 5/50
465/465 - 0s - loss: 0.4578 - accuracy: 0.0026 - val_loss: 0.4476 - val_accuracy: 0.0030 - 450ms/epoch - 967us/step
Epoch 6/50
465/465 - 0s - loss: 0.4469 - accuracy: 0.0026 - val_loss: 0.4422 - val_accuracy: 0.0030 - 480ms/epoch - 1ms/step
Epoch 7/50
465/465 - 0s - loss: 0.4475 - accuracy: 0.0026 - val_loss: 0.4385 - val_accuracy: 0.0030 - 438ms/epoch - 942us/step
Epoch 8/50
465/465 - 0s - loss: 0.4520 - accuracy: 0.0026 - val_loss: 0.4392 - val_accuracy: 0.0030 - 459ms/epoch - 987